# Generated by Django 3.2.7 on 2021-10-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Employee',
        ),
    ]
