# Generated by Django 3.2.7 on 2021-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20211217_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='hobby',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
